Item sub category to revert to "Select an option" when the Item Categ…
UKHomeOffice/cop-react-components pull request #116
Opened 2022-08-19 09:40 UTC by Deepak-Bagrawat

Item sub category to revert to "Select an option" when the Item Category is changed.
https://support.cop.homeoffice.gov.uk/browse/EAB-867

2022-08-19 11:20 UTC, LewisClark-HO requested changes

2022-08-19 11:20 UTC, LewisClark-HO commented on src/Select/Select.jsx
> +  const [selectAnOption, setSelectAnOption] = useState(options || []);
I think `selectAnOption` isn't a great name for this as it doesn't really describe what the variable is. Maybe something like `cachedOptions` might work better?

2022-08-19 11:20 UTC, LewisClark-HO commented on src/Select/Select.jsx
> +  if(!selectAnOption || selectAnOption?.length !== options?.length ) {
I think `!selectAnOption` here isn't needed as `selectAnOption` should only every be `options` if it's valid, or an empty array (which is a 'truthy' value).

2022-08-19 11:20 UTC, LewisClark-HO commented on src/Select/Select.jsx
> +  if(!selectAnOption || selectAnOption?.length !== options?.length ) {
Also comparing the `length` of the two arrays isn't a great way to do this - what if `options` is a different list but has the same number of entries in it as `selectAnOption`?

2022-08-22 11:34 UTC, Deepak-Bagrawat commented on src/Select/Select.jsx
> +  if(!selectAnOption || selectAnOption?.length !== options?.length ) {
with the length now checking value also.

2022-08-22 13:26 UTC, LewisClark-HO commented
Also, some tests are failing after these changes have been made.

2022-08-22 14:51 UTC, Deepak-Bagrawat commented on src/Select/Select.jsx
> +        cachedOptions[0]?.id === options[0]?.id &&
Yes, from refdata all have id and I checked Terminal, team, sub-location, ports, grade JSON files all of them have id.

2022-08-22 15:42 UTC, Deepak-Bagrawat commented on src/Select/Select.jsx
> +        cachedOptions[0]?.id === options[0]?.id &&
replaced id with value,

2022-08-23 08:29 UTC, LewisClark-HO approved these changes

2022-08-23 08:30 UTC, LewisClark-HO commented
LGTM, thanks for making those changes :)

2022-08-23 09:15 UTC, merged