EAB-88 Add Checkbox component
UKHomeOffice/cop-react-components pull request #49
Opened 2022-01-25 17:24 UTC by gardnersam

2022-01-26 13:57 UTC, paulfgraham requested changes
I know it's a draft but thought I'd do a quick early review seeing as I saw the PR sitting there. 🙂

2022-01-26 13:57 UTC, paulfgraham commented on src/Checkboxes/Checkbox.jsx
> +import PropTypes from "prop-types";
We've used single quotes everywhere else. Can you set your IDE up to do that too, please? We ought to have a linting rule in place for this so we can be consistent throughout the library.

2022-01-26 13:57 UTC, paulfgraham commented on src/Checkboxes/Checkbox.jsx
> +import { classBuilder } from "../utils/Utils";
The ordering of imports should follow a pattern along the lines of:
```
// Global imports

// Local imports

// [Styles - this can be with local imports or separated out]
```

Additionally, the imports should be ordered appropriately (by level, and then alphabetically). This should also be added as a linting rule for consistency. That linting rule may well remove the `// Global` and `// Local` comments but so long as we're consistent, that's fine.

See `Radios.jsx` for an example of ordered imports.

2022-01-26 13:57 UTC, paulfgraham commented on src/Checkboxes/Checkbox.jsx
> +      {option?.hint && (
You've specified that `option` is required, below, so there's no need to check for it here.
```suggestion
      {option.hint && (
```

2022-01-26 13:57 UTC, paulfgraham commented on src/Checkboxes/Checkbox.test.js
> +import Checkbox from "./Checkbox";
The imports on 2 and 3 should be on a single line.

2022-01-26 13:57 UTC, paulfgraham commented on src/Checkboxes/Checkboxes.jsx
> +  hint,
This shouldn't be here - `hint` is part of the `FormGroup` component.

2022-01-26 13:57 UTC, paulfgraham commented on src/Checkboxes/Checkboxes.jsx
> +      {hint && (
This whole block shouldn't be here - `hint` is part of the `FormGroup` component.

2022-01-26 13:57 UTC, paulfgraham commented on src/Checkboxes/Checkboxes.stories.mdx
> +            fieldId="where-do-you-live-checkboxes"
Probably not the right `id`, considering the question and options. 🙂

2022-01-26 13:57 UTC, paulfgraham commented on src/Checkboxes/Checkboxes.stories.mdx
> +        hint="Select all that apply"
As mentioned, the `hint` should not be part of the `Checkboxes` component because it is already where it belongs, within the `FormGroup` component.

2022-01-26 13:57 UTC, paulfgraham commented on src/Checkboxes/Checkboxes.test.js
> +import { ContextExclusionPlugin } from "webpack";
It's showing a warning for this anyway but this is failing linting because it's an unused import. We should add a pre-commit hook to make sure all tests pass and linting shows no errors before the commit/push is allowed.

2022-01-26 13:57 UTC, paulfgraham commented on src/index.js
> +import Checkboxes from './Checkboxes';
This import should be placed in the right spot alphabetically.

2022-01-26 13:57 UTC, paulfgraham commented on src/index.js
> +  Checkboxes
And this export should also be placed in the right spot alphabetically.

2022-01-28 11:08 UTC, gardnersam commented on src/Checkboxes/Checkbox.jsx
> +import PropTypes from "prop-types";
Yep, all files updated with single quotes

2022-01-28 11:09 UTC, gardnersam commented on src/Checkboxes/Checkbox.jsx
> +import { classBuilder } from "../utils/Utils";
Agree on the linting rule, sounds like there are a few bits we could add in for that. I've fixed these files.

2022-01-28 11:09 UTC, gardnersam commented on src/Checkboxes/Checkbox.jsx
> +      {option?.hint && (
Good spot, updated

2022-01-28 11:09 UTC, gardnersam commented on src/Checkboxes/Checkboxes.jsx
> +  hint,
I've taken the hint out of the Checkboxes component

2022-01-28 11:11 UTC, gardnersam commented on src/index.js
> +  Checkboxes
Updated

2022-01-28 11:11 UTC, gardnersam commented on src/index.js
> +import Checkboxes from './Checkboxes';
Updated

2022-01-28 11:11 UTC, gardnersam commented on src/Checkboxes/Checkboxes.test.js
> +import { ContextExclusionPlugin } from "webpack";
Good spot, updated, think I need to change the colour scheme in my ide so this stands out better

2022-01-28 12:03 UTC, paulfgraham reviewed
I think this just now needs a unit test for a `Checkbox` with a hint, which is so far not covered. Otherwise, looking good. 🙂

2022-01-28 12:34 UTC, paulfgraham approved these changes
Thank you for making the requested changes, @gardnersam. This all looks good. 👍

2022-01-28 14:06 UTC, paulfgraham commented
Replaced by https://github.com/UKHomeOffice/cop-react-components/pull/51, which had signed commits.

2022-01-28 14:06 UTC, closed without merging