EAB-85 Add Date Input component
UKHomeOffice/cop-react-components pull request #52
Opened 2022-02-01 15:14 UTC by gardnersam

2022-02-01 15:37 UTC, paulfgraham commented on src/DateInput/DateInput.jsx
> +    setDate({...date, [event.target.name] : event.target.value})
This isn't going to have quite the effect you're expecting... or, at least, it's not guaranteed to. To do this cleanly, you want the current state, which is achieved by passing a function to `setDate`, where the function receives the current state:
```suggestion
    setDate(prev => ({...prev, [event.target.name] : event.target.value}));
```

Basically, there's an asynchronous nature to this and if you fire `onChange` multiple times in rapid succession (such as someone typing quickly) with your code, you're not guaranteed to capture all the changes. This has caught me out countless times!

2022-02-01 15:41 UTC, paulfgraham commented on src/DateInput/DateInput.jsx
> +        <div className='govuk-form-group'>
Hmmm... I feel like this whole block could be made up of `<FormGroup />` and `<TextInput />` elements, rather than redoing the markup.

2022-02-01 15:42 UTC, paulfgraham commented on src/DateInput/DateInput.jsx
> +        <div className='govuk-form-group'>
And, actually, does each of the fields need its own form group or can it simply wrap the whole thing? 🤔

2022-02-01 15:44 UTC, paulfgraham commented on src/DateInput/DateInput.jsx
> +  day,
Why are `day`, `month`, and `year` separate properties and not simply wrapped up into a `value` object? This implementation puts the onus on the developer to split a date into its constituent parts when I think it'd be cleaner to handle it within the component. 🤔

2022-02-01 15:45 UTC, paulfgraham commented on src/DateInput/DateInput.jsx
> +  id,
For consistency with the other components, I think you're also going to need a `fieldId`.

2022-02-01 15:46 UTC, paulfgraham commented on src/DateInput/DateInput.jsx
> +  ...attrs
I think we also need a `readonly` flag here and a readonly version of the output. Within the COP React Form Renderer, we expect editable components to have a readonly option for rendering on, for example, the **Check your answers** screen.

2022-02-01 15:49 UTC, paulfgraham commented on src/DateInput/DateInput.test.js
> +import '@testing-library/jest-dom';
What is this import doing? 🤔

2022-02-01 16:57 UTC, gardnersam commented on src/DateInput/DateInput.test.js
> +import '@testing-library/jest-dom';
It provides the toHaveTextContent() function

2022-02-02 11:14 UTC, paulfgraham commented on src/DateInput/DateInput.test.js
> +import '@testing-library/jest-dom';
`import { toHaveTextContent } from '@testing-library/jest-dom';`?

Alternatively, you could just do:
`expect(whatever.textContent).toEqual(specifiedValue);`
or
`expect(whatever.textContent).toContain(specifiedValue);`

2022-02-02 11:15 UTC, paulfgraham commented on src/DateInput/DateInput.test.js
> +import '@testing-library/jest-dom';
We're not using `toHaveTextContent` anywhere else within this library, nor within the Form Renderer one. Not saying we _shouldn't_ exactly... but just pointing out we're currently doing it differently wherever else we're checking for the `textContent` (in the Form Renderer).

2022-02-02 14:20 UTC, gardnersam commented on src/DateInput/DateInput.test.js
> +import '@testing-library/jest-dom';
Fair point, I've swapped to checking .textContent for consistency

2022-02-02 14:20 UTC, gardnersam commented on src/DateInput/DateInput.jsx
> +  ...attrs
I've added a readonly flag and an early return for it

2022-02-02 14:20 UTC, gardnersam commented on src/DateInput/DateInput.jsx
> +  id,
I've added this and updated where appropriate

2022-02-02 14:21 UTC, gardnersam commented on src/DateInput/DateInput.jsx
> +        <div className='govuk-form-group'>
I've replaced the inputs with TextInputs as you suggest and you're also right about not needing the individual form group wrappings so removed that aswell

2022-02-02 14:22 UTC, gardnersam commented on src/DateInput/DateInput.jsx
> +    setDate({...date, [event.target.name] : event.target.value})
After swapping to TextInputs I realised what I was doing here was unrequired so the useState is removed completely

2022-02-02 14:23 UTC, gardnersam commented
I forgot to sign one of the commits, I've attempted to resign but there's a chance github may still be unhappy

2022-02-03 16:57 UTC, paulfgraham requested changes

2022-02-03 16:57 UTC, paulfgraham commented on src/DateInput/DateInput.jsx
> +    return (
Could this not simply be:
```
return (
  <Readonly id={id} classModifiers={classModifiers} className={className} {...attrs}>
    {value}
  </Readonly>
)
```

Or, if `value` absolutely, positively _has_ to be an object rather than a simple date string:
```
return (
  <Readonly id={id} classModifiers={classModifiers} className={className} {...attrs}>
    {value.day}/{value.month}/{value.year}
  </Readonly>
)
```

I definitely don't think you're going to want the "Day", "Month", and "Year" labels in a readonly format, are you? I think this might be one that needs to be run past the UX team.

2022-02-03 16:57 UTC, paulfgraham commented on src/DateInput/DateInput.jsx
> +        ></TextInput>
This can self-close:
```suggestion
        />
```

2022-02-03 16:57 UTC, paulfgraham commented on src/DateInput/DateInput.jsx
> +        ></TextInput>
The same for the ones below.

2022-02-03 16:57 UTC, paulfgraham commented on src/DateInput/DateInput.stories.mdx
> +import TextInput from '../TextInput/TextInput';
It doesn't look like you're using `TextInput` in here...

2022-02-03 16:57 UTC, paulfgraham commented on src/DateInput/DateInput.jsx
> +import TextInput from '../TextInput/TextInput';
```suggestion
import TextInput from '../TextInput';
```

There's a barrel file (`index.js`) sitting inside of each component directory so you don't need the second `TextInput` here.

2022-02-03 16:57 UTC, paulfgraham commented on src/DateInput/DateInput.jsx
> +import { DEFAULT_CLASS as DEFAULT_LABEL_CLASS } from '../Label/Label';
You don't need to import this because... see below.

2022-02-03 16:57 UTC, paulfgraham commented on src/DateInput/DateInput.jsx
> +          <label className={`${DEFAULT_LABEL_CLASS} ${classes('label')}`} htmlFor={`${id}-day`}>
You don't need to provide `DEFAULT_LABEL_CLASS` to the `className` attribute because it's already in the `classBlock` within the `Label` component. Adding it here is redundant.

2022-02-03 16:57 UTC, paulfgraham commented on src/DateInput/DateInput.jsx
> +          classBlock={`govuk-input ${classes('input')} govuk-input--width-2 ${
This isn't really following the BEM pattern. This should look something like this:
```
<TextInput
  id={`${id}-day`}
  fieldId={`${fieldId}-day`}
  value={value?.day}
  onChange={onChange}
  error={error?.day ? 'error' : ''}
  className={classes('input')}
  classModifiers="width-2"
/>
```

The `error` one is a bit squiffy here but the `TextInput` expects a string. You could consider adjusting the `TextInput` property to accept either a string or a boolean and then just pass `error?.day`.

2022-02-03 16:57 UTC, paulfgraham commented on src/DateInput/DateInput.jsx
> +          classBlock={`govuk-input ${classes('input')} govuk-input--width-2 ${
This all also applies to the other `TextInput` elements in here.

2022-02-04 16:51 UTC, gardnersam commented on src/DateInput/DateInput.jsx
> +    return (
The answer from the UX team is "Dates should usually be written out in full, 7 February 2022". So I've added a converter from the month number to the word version and formatted the output to match.

2022-02-04 16:51 UTC, gardnersam commented on src/DateInput/DateInput.jsx
> +        ></TextInput>
I've updated these to self close

2022-02-04 16:52 UTC, gardnersam commented on src/DateInput/DateInput.stories.mdx
> +import TextInput from '../TextInput/TextInput';
Good spot, removed

2022-02-04 16:52 UTC, gardnersam commented on src/DateInput/DateInput.jsx
> +import TextInput from '../TextInput/TextInput';
Updated to use the barrel file

2022-02-04 16:52 UTC, gardnersam commented on src/DateInput/DateInput.jsx
> +          <label className={`${DEFAULT_LABEL_CLASS} ${classes('label')}`} htmlFor={`${id}-day`}>
Swapped to Label (capital L) and removed the DEFAULT_LABEL_CLASS

2022-02-04 16:54 UTC, gardnersam commented on src/DateInput/DateInput.jsx
> +          classBlock={`govuk-input ${classes('input')} govuk-input--width-2 ${
I've updated these and believe they are now done in the proper pattern

2022-02-07 09:12 UTC, paulfgraham approved these changes
Thank you for making the requested changes, @gardnersam. Approved. 👍

2022-02-07 10:10 UTC, merged