EAB-123 Add onChange and readonly handling to checkboxes
UKHomeOffice/cop-react-components pull request #66
Opened 2022-02-24 14:13 UTC by gardnersam

2022-02-24 14:39 UTC, paulfgraham requested changes
I think the readonly rendering isn't quite right but needs some UX input. A couple of other suggestions for change in here too.

I've also been a bit fussy with some `if ( ... )` in preference to `if( ... )` but it's just because the rest of the code is nice and clean.

2022-02-24 14:39 UTC, paulfgraham commented on package.json
> +  "version": "1.0.1-alpha",
```suggestion
  "version": "1.0.0-beta",
```

2022-02-24 14:39 UTC, paulfgraham commented on src/Checkboxes/Checkboxes.jsx
> +      setSelection(selection.filter((s) => s !== target.value));
```suggestion
      setSelection(oldSelection => oldSelection.filter((s) => s !== target.value));
```

(Personally, I'd use the variable name `prev` rather than `oldSelection`... but I was being consistent with line 31.)

2022-02-24 14:39 UTC, paulfgraham commented on src/Checkboxes/Checkboxes.jsx
> +        {value.join(' ')}
This doesn't look right to me for two reasons:
1.  We want it to show the label, not the underlying value.
2. Separating by spaces won't work if the label (see 1) contains a space. It should either be separated by commas or (my preference) by semicolons. This should be checked with UX, though. I don't know if there are examples.

2022-02-24 14:39 UTC, paulfgraham commented on src/Checkboxes/Checkboxes.jsx
> +    if(typeof onChange === 'function' && selection !== value){
```suggestion
    if (typeof onChange === 'function' && selection !== value){
```

2022-02-25 14:12 UTC, gardnersam commented on src/Checkboxes/Checkboxes.jsx
> +      setSelection(selection.filter((s) => s !== target.value));
Swapped to prev for both

2022-02-25 14:12 UTC, gardnersam commented on src/Checkboxes/Checkboxes.jsx
> +        {value.join(' ')}
I've spoken to UX and they have requested each item be on a new line so I've updated to do this with the labels

2022-02-25 14:31 UTC, paulfgraham requested changes
I think the rendering of the readonly could do with some null checking on the `options` and I've proposed what I think is a cleaner way of doing the rendering that doesn't result in an extraneous `<br />` at the end.

2022-02-25 14:31 UTC, paulfgraham commented on src/Checkboxes/Checkboxes.jsx
> +        {value.map((currentValue, index) => {
You're already setting up `selection` in the state so it's better to use that - it takes care of a missing `value` with an empty array.

Also, it might be cleaner to do this as:
```
{options && options.filter(o => selection.contains(o.value)).map(opt => (
  return <div key={opt.value}>{opt.label}</div>;
)}
```

That would take care of the line breaks as a `<div>` is a block element. Using the `index` as the key will often fail linters as it can impact performance and affect state - so using the option's `value` would be better.

2022-02-25 14:54 UTC, gardnersam commented on src/Checkboxes/Checkboxes.jsx
> +        {value.map((currentValue, index) => {
Good solution, I've swapped to this

2022-02-25 14:56 UTC, paulfgraham approved these changes
Thanks for making the requested changes, @gardnersam, and making this a fully-featured component. 😁

2022-02-25 14:58 UTC, merged