Added new Time component
UKHomeOffice/cop-react-components pull request #73
Opened 2022-03-30 11:35 UTC by Deepak-Bagrawat

https://support.cop.homeoffice.gov.uk/browse/EAB-87

2022-03-30 12:36 UTC, paulfgraham requested changes
A few things that definitely need changing. There's also quite a lot of extraneous blank lines that should be removed.

2022-03-30 12:36 UTC, paulfgraham commented on src/TimeInput/TimeInput.jsx
> +      <div className={classes('item')}>
This ought to be a `FormGroup`, the same as for the `DateInput` component.

2022-03-30 12:36 UTC, paulfgraham commented on src/TimeInput/TimeInput.jsx
> +  value: PropTypes.shape({
This should be a string, the same as for the `DateInput` component.

2022-03-30 12:36 UTC, paulfgraham commented on src/TimeInput/TimeInput.jsx
> +  error: PropTypes.shape({
This should be a string.

2022-03-30 12:36 UTC, paulfgraham commented on src/TimeInput/TimeInput.jsx
> +      <div className={classes('item')}>
The same here: `FormGroup`.

2022-03-30 12:36 UTC, paulfgraham commented on src/TimeInput/TimeInput.jsx
> +import { classBuilder } from '../utils/Utils';
These imports are not ordered...

2022-03-30 12:36 UTC, paulfgraham commented on src/TimeInput/TimeInput.jsx
> +export const DEFAULT_CLASS = 'govuk-date-input';
Why is this a _date_ input?

2022-03-31 08:14 UTC, Deepak-Bagrawat commented on src/TimeInput/TimeInput.jsx
> +export const DEFAULT_CLASS = 'govuk-date-input';
Hi Paul, I have resolved all comments apart from this. I used govuk-date-input because I need same styling as date-input component and Unable to find govuk-time-input component under the 'node_modules/govuk-frontend/govuk/components/' folder. 
Please can you suggest what's the best way to add time-input?

2022-03-31 08:14 UTC, paulfgraham requested changes

2022-03-31 08:14 UTC, paulfgraham commented on src/TimeInput/TimeInput.jsx
> +      <div className={classes('item')}>
What you've done isn't what I was proposing at all. Have a look at the `DateInput` component.

2022-03-31 08:14 UTC, paulfgraham commented on src/TimeInput/TimeInput.test.js
> +
Please remove all this extra whitespace.

2022-03-31 08:15 UTC, paulfgraham commented on src/TimeInput/TimeInput.jsx
> +          value={value?.hour}
Since the `value` is now a string, this isn't going to work.

2022-03-31 08:16 UTC, paulfgraham commented on src/TimeInput/TimeInput.jsx
> +        {value?.hour}:{value?.minute }
Since the `value` is now a string, this isn't going to work.

2022-03-31 08:17 UTC, paulfgraham commented on src/TimeInput/TimeInput.test.js
> +        value={{ hour:14, minute:30 }}
How can this possibly work when `value` is expected to be a string?

2022-03-31 08:18 UTC, paulfgraham commented on src/TimeInput/TimeInput.test.js
> +
There needs to be tests that setting the `value` (as a string) actually populates the fields correctly and that changing one of those fields changes the `value` (to an appropriately formatted string).

2022-04-04 09:50 UTC, Deepak-Bagrawat commented on src/TimeInput/TimeInput.jsx
> +      <div className={classes('item')}>
Updated TimeInput component according to DateInput component

2022-04-04 09:51 UTC, Deepak-Bagrawat commented on src/TimeInput/TimeInput.jsx
> +  value: PropTypes.shape({
Done

2022-04-04 09:51 UTC, Deepak-Bagrawat commented on src/TimeInput/TimeInput.jsx
> +  error: PropTypes.shape({
Done

2022-04-04 14:21 UTC, gardnersam reviewed
Few comments

2022-04-04 14:21 UTC, gardnersam commented on src/TimeInput/TimeInput.jsx
> +
Can we remove these spare lines?

2022-04-04 14:21 UTC, gardnersam commented on src/TimeInput/TimeInput.jsx
> +  classBlock,
The other components all put the class fields (Block, Modifier and Name) at the end above ...attrs

2022-04-04 14:21 UTC, gardnersam commented on src/TimeInput/TimeInput.jsx
> +            classModifiers={`width-${part.width}`}
This is always 2, is it easier to just put 2 here

2022-04-04 15:45 UTC, gardnersam commented on src/TimeInput/TimeInput.test.js
> +    expect(minuteInput.classList).not.toContain('govuk-input-error')
Minute error is set to true so there should be an error here

2022-04-04 15:45 UTC, gardnersam commented on src/TimeInput/TimeInput.test.js
> +      value: '20:30'
You set the minutes to 40, so shouldnt this be 20:40?

2022-04-06 08:52 UTC, gardnersam approved these changes
Looks good!

2022-04-07 09:01 UTC, paulfgraham requested changes

2022-04-07 09:01 UTC, paulfgraham commented on src/TimeInput/TimeInput.test.js
> +
Please remove this extraneous blank line.

2022-04-07 09:01 UTC, paulfgraham commented on src/index.js
> +import TimeInput from './TimeInput/TimeInput';
This is not in order, compared to the other imports. Also, you should import directly from `'./TimeInput';` without the extra `TimeInput`, just like the other imports.

2022-04-07 09:03 UTC, paulfgraham commented on src/TimeInput/TimeInput.jsx
> +  error: PropTypes.shape({
I left another comment about this one... because it's still not a string.

2022-04-07 09:04 UTC, paulfgraham commented on src/TimeInput/TimeInput.test.js
> +
Please remove this extraneous blank line.

2022-04-07 09:07 UTC, paulfgraham commented on src/TimeInput/TimeInput.jsx
> +import PropTypes from "prop-types";
Ah, yes, you _did_ change them all to double quotes after I last reviewed it. I suspect your IDE was being tricksy.

2022-06-16 08:45 UTC, closed without merging