COP-10557 - Multi Select Autocomplete
UKHomeOffice/cop-react-components pull request #84
Opened 2022-05-23 16:03 UTC by charles474

### Description
Added a `MultiSelectAutocomplete` component, which runs in either a single selection or a multi selection mode.

https://support.cop.homeoffice.gov.uk/browse/COP-10557

### To test
Covered by accompanying unit tests and Storybook stories.

2022-05-23 16:21 UTC, paulfgraham requested changes
A few bits and pieces but I've not done a full review yet...

2022-05-23 16:21 UTC, paulfgraham commented on src/index.js
>  };
This needs a carriage return at the end. Not sure why it's not there already but can you add one, please?

2022-05-23 16:21 UTC, paulfgraham commented on src/index.js
> +  MultiSelectAutocomplete
This should be in alphabetical order.

2022-05-23 16:21 UTC, paulfgraham commented on src/index.js
> +import MultiSelectAutocomplete from './MultiSelectAutocomplete';
This should be in alphabetical order.

2022-05-23 16:21 UTC, paulfgraham commented on src/MultiSelectAutocomplete/Utils.js
> +const INTERPOLATE_REGEX = /\${[^{]+}/g;
This entire file already exists within this project at `src/utils/Utils.js`. 🤔

2022-05-23 16:21 UTC, paulfgraham commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.scss
> +      padding: 5px;
Seeing as you're using `rems` in the lines below, this should be in the same units:
```suggestion
      padding: 0.3125rem;
```
(5 / 16 = 0.3125)

2022-05-23 16:21 UTC, paulfgraham commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.scss
> +  .hods-multi-select-autocomplete {
How come this block is detached from the one above?

2022-05-23 16:21 UTC, paulfgraham commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +  templates: _templates,
Is there a reason why this doesn't have the same signature as the `Autocomplete`?

2022-05-23 16:21 UTC, paulfgraham commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +          ...attrs.options
Ah, _there_ is `options`. Can you make this an actual property, rather than having it come from `attrs`? 🙂

2022-05-23 16:21 UTC, paulfgraham commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +        styles={{
This whole block is pretty confusing to follow. It's going to be a nightmare to maintain or change like this.

2022-05-23 19:17 UTC, charles474 commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +  templates: _templates,
As for `source`, in the current existing implementation of `Autocomplete`, it seems to be used primarily to get the `getFiilterFunction` within that component, the `MultiSelectAutocomplete` has a very basic filter function hence why source is not used here. Initially tried to salvage it however the current implementation broke `react-select`'s functionality.

2022-05-24 08:01 UTC, paulfgraham commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +  templates: _templates,
Yeah, that's fair enough about `source`. I had a better look through the code and what you've described is correct. I think `options` should still be a named property, though. 🙂

2022-05-24 08:02 UTC, charles474 commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +  templates: _templates,
`options` i believe has now been made a named property, same for `isMulti` 😄

2022-05-24 10:01 UTC, paulfgraham commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +    option: (provided, state) => ({
Suggestion:
```javascript
const customStyles = {
  option: (provided, state) => ({
    ...provided,
    ...(state.isFocused ? STATE_COLOURS.FOCUSED : STATE_COLOURS.UNFOCUSED)
  })
};
```
I've also separated out the colour states as constants to make it easier to see what they mean.
```javascript
const STATE_COLOURS = {
  FOCUSED: { backgroundColor: GOVUK_COLOR_BLUE, color: GOV_COLOR_WHITE },
  UNFOCUSED: { backgroundColor: GOV_COLOR_NONE, color: GOV_COLOR_BLACK }
};
```

2022-05-24 10:27 UTC, paulfgraham commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +  className: _className,
```suggestion
  classBlock,
  classModifiers: _classModifiers,
  className,
```

2022-05-24 10:28 UTC, paulfgraham commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +  className: PropTypes.string
```suggestion
  classBlock: PropTypes.string,
  classModifers: PropTypes.onOfType([PropTypes.string, PropTypes.arrayOf(PropTypes.string)]),
  className: PropTypes.string
```

2022-05-24 10:28 UTC, paulfgraham commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +  classBlock: DEFAULT_CLASS,
```suggestion
  classBlock: DEFAULT_CLASS,
  classModifiers: [],
```

2022-05-24 10:45 UTC, paulfgraham commented
Ignore the bit about `classBuilder`, as discussed on Teams call.

2022-05-24 10:47 UTC, charles474 commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +  const className = concatClasses(_className, error ? 'error' : undefined);
Ignoring for now as discussed.

2022-05-24 10:48 UTC, charles474 commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +    <div className={`${DEFAULT_CLASS}__outer-wrapper ${className ?? ''}`}>
Ignoring for now as discussed

2022-05-24 10:51 UTC, charles474 commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +  className: _className,
Ignoring as disscussed.

2022-05-24 10:51 UTC, charles474 commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +  className: PropTypes.string
Ignoring as disscussed.

2022-05-24 11:01 UTC, charles474 commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +      <Readonly id={id} className={className} {...attrs}>
Ignoring as discussed.

2022-05-24 13:37 UTC, paulfgraham commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +  GOVUK_COLOR_BLUE: '#1d70b8',
This doesn't need the whole `GOVUK_COLOR_` prefix when it's inside of an object like this...
```suggestion
  BLUE: '#1d70b8',
```

2022-05-24 13:37 UTC, paulfgraham commented on src/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
> +const COLORS = {
```suggestion
const COLOURS = {
```

🥺

2022-05-24 13:43 UTC, paulfgraham commented on src/storybook-resources/Countries-sb.js
> +    MultiSelectCountriesAsRefData.push({
In what way is this different from just `CountriesAsRefData`? I'm not sure why you need a separate one...?

2022-05-24 14:54 UTC, paulfgraham approved these changes

2022-05-24 14:55 UTC, merged