Update onchange for radios to handle nested components and collections
UKHomeOffice/cop-react-components pull request #91
Opened 2022-06-14 16:12 UTC by gardnersam

The onChange function within the radios component was submitting all changes it caught with the fieldId of the Radios component, this meant that changes to nested components were being caught and also passed up as changes with the Radios fieldId. The value for the Radios component was then set to the value of the nested component. 

Collections have component names like `people[0].title` where as things outside of collections would just have names like `title`. This PR deconstructs the collection names to extract the original fieldId and then only calls onChange if the change has actually originated from the Radios component. Changes to the nested component are passed up by their own onChange handlers.

2022-06-14 16:29 UTC, paulfgraham requested changes
Can we add a lint rule to stop this thing with no spaces are extra spaces all over the code? 😝

2022-06-14 16:29 UTC, paulfgraham commented on src/Radios/Radios.jsx
> +    if(nameParts.length > 1){
```suggestion
    if (nameParts.length > 1) {
```

2022-06-14 16:29 UTC, paulfgraham commented on src/Radios/Radios.jsx
> +      output = nameParts[1];
This can't just be `nameParts[1]` because it could easily be more deeply nested than this. This would work, however:
```suggestion
      output = nameParts.pop();
```

2022-06-14 16:29 UTC, paulfgraham commented on src/Radios/Radios.jsx
> +    if (typeof onChange === 'function' && fieldId === output ) {
```suggestion
    if (typeof onChange === 'function' && fieldId === output) {
```

2022-06-15 11:37 UTC, gardnersam commented on src/Radios/Radios.jsx
> +      output = nameParts[1];
Good suggestion, updated to pop off the last part now

2022-06-15 11:38 UTC, gardnersam commented on src/Radios/Radios.jsx
> +    if (typeof onChange === 'function' && fieldId === output ) {
Fixed this

2022-06-15 15:15 UTC, paulfgraham approved these changes

2022-06-15 15:24 UTC, merged